"use client";

import { useEffect, useMemo, useState } from "react";
import { X, Trash2, GripVertical } from "lucide-react";
import { documentTypeLabel, documentTypes, fieldsByDocumentType, type DocumentType, type TemplateField } from "@/lib/templateOptions";

export interface TemplateDraft {
  id?: string;
  name: string;
  templateKey: string;
  documentType: DocumentType;
  version: number;
  isDefault: boolean;
  fields: TemplateField[];
}

function generatePreviewHtml(companyName: string, fields: TemplateField[]): string {
  const headerFields = fields.filter((f) => f.position === "header");
  const bodyFields = fields.filter((f) => f.position === "body");
  const footerFields = fields.filter((f) => f.position === "footer");

  const renderField = (field: TemplateField) => {
    const value = `{{${field.key}}}`;
    return `
      <div class="field">
        <div class="label">${field.label}</div>
        <div class="value">${field.type === "textarea" ? `<div class="textarea">${value}</div>` : value}${field.type === "currency" ? " USDC" : ""}</div>
      </div>`;
  };

  return `<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: Arial, sans-serif; padding: 40px; max-width: 600px; margin: 0 auto; color: #333; }
  h1 { border-bottom: 2px solid #7FD9B0; padding-bottom: 10px; margin-bottom: 5px; }
  .subtitle { color: #666; margin-bottom: 30px; }
  .section { margin: 20px 0; }
  .section-title { font-size: 12px; color: #999; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
  .field { margin: 12px 0; }
  .label { color: #666; font-size: 12px; }
  .value { font-size: 16px; color: #333; }
  .textarea { background: #f9f9f9; padding: 12px; border-radius: 6px; min-height: 60px; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 11px; }
  .header-section { margin-bottom: 30px; }
  .company { font-size: 24px; font-weight: bold; }
</style>
</head>
<body>
  <div class="header-section">
    <div class="company">{{companyName}}</div>
    <div class="subtitle">Document</div>
    ${headerFields.map(renderField).join("")}
  </div>
  
  <div class="section">
    <div class="section-title">Details</div>
    ${bodyFields.map(renderField).join("")}
  </div>
  
  <div class="footer">
    ${footerFields.map(renderField).join("")}
    <div style="margin-top: 10px">Generated by Tamarind</div>
  </div>
</body>
</html>`;
}

function renderPreviewHtml(html: string, companyName: string, fields: TemplateField[]): string {
  let preview = html;
  preview = preview.replace(/\{\{companyName\}\}/g, companyName || "Company Name");
  
  const sampleValues: Record<string, string> = {
    senderName: "Acme Corp",
    recipientName: "John Doe",
    amount: "1,000.00",
    currency: "USDC",
    paymentDate: new Date().toLocaleDateString(),
    chain: "Base Sepolia",
    txHash: "0x1234...abcd",
    settlementId: "STL-001",
    merkleRoot: "0xabcd...1234",
    status: "Completed",
    notes: "Payment for services",
    invoiceNumber: "INV-1001",
    issueDate: new Date().toLocaleDateString(),
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString(),
    lineItems: "Professional services\n1 x 1,000.00",
    subtotal: "1,000.00",
    tax: "0.00",
    total: "1,000.00",
    approvalStatus: "Pending",
    employeeName: "Alex Morgan",
    payPeriod: "July 2026",
    grossPay: "5,000.00",
    deductions: "800.00",
    netPay: "4,200.00",
  };
  
  for (const field of fields) {
    const regex = new RegExp(`\\{\\{${field.key}\\}\\}`, "g");
    const sampleValue = sampleValues[field.key] || `[${field.label}]`;
    preview = preview.replace(regex, sampleValue);
  }
  
  return preview;
}

export default function TemplateEditor({ template, onClose, onSave, error }: { template: TemplateDraft | null; onClose: () => void; onSave: (draft: TemplateDraft) => Promise<void>; error?: string }) {
  const [name, setName] = useState(template?.name || "");
  const [documentType, setDocumentType] = useState<DocumentType>(template?.documentType || "payment");
  const [fields, setFields] = useState<TemplateField[]>(template?.fields || fieldsByDocumentType.payment.slice(0, 6));
  const [saving, setSaving] = useState(false);
  const [previewTab, setPreviewTab] = useState<"preview" | "fields">("preview");

  useEffect(() => { 
    if (!template) {
      const defaultFields = fieldsByDocumentType[documentType];
      setFields(defaultFields.slice(0, documentType === "invoice" ? 8 : 6));
    }
  }, [documentType, template]);

  const available = useMemo(() => fieldsByDocumentType[documentType].filter((field) => !fields.some((item) => item.key === field.key)), [documentType, fields]);

  function addField(key: string) { 
    const field = fieldsByDocumentType[documentType].find((item) => item.key === key); 
    if (field) setFields((current) => [...current, field]); 
  }

  function removeField(index: number) {
    const field = fields[index];
    if (field?.locked) return;
    setFields((current) => current.filter((_, i) => i !== index));
  }

  function updateField(index: number, updates: Partial<TemplateField>) { 
    setFields((current) => current.map((field, position) => position === index ? { ...field, ...updates } : field)); 
  }

  function moveField(index: number, direction: -1 | 1) { 
    const next = index + direction; 
    if (next < 0 || next >= fields.length) return; 
    const copy = [...fields]; 
    [copy[index], copy[next]] = [copy[next], copy[index]]; 
    setFields(copy); 
  }

  async function save() { 
    if (!name.trim() || fields.length === 0) return; 
    setSaving(true); 
    await onSave({ 
      id: template?.id, 
      name: name.trim(), 
      templateKey: template?.templateKey || `${documentType}-${Date.now()}`, 
      documentType, 
      version: template?.version || 1, 
      isDefault: template?.isDefault || false, 
      fields 
    }); 
    setSaving(false); 
  }

  const previewHtml = useMemo(() => generatePreviewHtml(name, fields), [name, fields]);
  const samplePreviewHtml = useMemo(() => renderPreviewHtml(previewHtml, name, fields), [previewHtml, name, fields]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/40 px-6">
      <div className="flex max-h-[90vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl border border-hair bg-panel shadow-xl">
        <div className="flex items-center justify-between border-b border-hair px-6 py-4">
          <div>
            <p className="text-[11px] font-mono uppercase tracking-wide text-sub">Template editor</p>
            <h2 className="mt-1 text-lg font-semibold text-ink">{template ? "Edit draft" : "New template"}</h2>
          </div>
          <button onClick={onClose} className="p-1 text-sub hover:text-ink" aria-label="Close">
            <X size={18} />
          </button>
        </div>
        
        {error && (
          <div className="mx-6 mt-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
            {error}
          </div>
        )}
        
        <div className="grid min-h-0 flex-1 md:grid-cols-2">
          <div className="overflow-y-auto border-b border-hair p-6 md:border-b-0 md:border-r">
            <label className="block text-sm font-medium text-ink">
              Template name
              <input 
                value={name} 
                onChange={(event) => setName(event.target.value)} 
                placeholder="Payment receipt" 
                className="mt-2 w-full rounded-lg border border-hair bg-paper px-4 py-2.5 text-sm font-normal text-ink outline-none focus:border-indigo" 
              />
            </label>
            
            <label className="mt-5 block text-sm font-medium text-ink">
              Document type
              <select 
                value={documentType} 
                disabled={Boolean(template)} 
                onChange={(event) => setDocumentType(event.target.value as DocumentType)} 
                className="mt-2 w-full rounded-lg border border-hair bg-panel px-4 py-2.5 text-sm font-normal text-ink outline-none focus:border-indigo"
              >
                {documentTypes.map((type) => (
                  <option key={type.value} value={type.value}>{type.label}</option>
                ))}
              </select>
            </label>
            
            <div className="mt-6">
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium text-ink">Fields</p>
                <select 
                  value="" 
                  onChange={(event) => { addField(event.target.value); event.target.value = ""; }} 
                  className="rounded-md border border-hair bg-panel px-2 py-1.5 text-xs text-sub"
                >
                  <option value="">Add field...</option>
                  {available.map((field) => (
                    <option key={field.key} value={field.key}>{field.label}</option>
                  ))}
                </select>
              </div>
              
              <div className="mt-3 space-y-2">
                {fields.map((field, i) => (
                  <div key={field.key} className="flex items-center gap-2 rounded-lg border border-hair bg-paper px-3 py-2">
                    <GripVertical size={14} className="text-sub" />
                    <span className="flex-1 text-sm text-ink">{field.label}</span>
                    <span className="text-[10px] text-sub">{field.position}</span>
                    {!field.locked && (
                      <button 
                        onClick={() => removeField(i)} 
                        className="p-1 text-sub hover:text-coral"
                        aria-label="Remove field"
                      >
                        <Trash2 size={14} />
                      </button>
                    )}
                    {field.locked && (
                      <span className="text-[10px] text-sub italic">locked</span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
          
          <div className="flex min-h-0 flex-col">
            <div className="flex border-b border-hair">
              <button
                onClick={() => setPreviewTab("preview")}
                className={`flex-1 py-3 text-sm font-medium transition-colors ${
                  previewTab === "preview" ? "text-ink border-b-2 border-ink" : "text-sub hover:text-ink"
                }`}
              >
                Preview
              </button>
              <button
                onClick={() => setPreviewTab("fields")}
                className={`flex-1 py-3 text-sm font-medium transition-colors ${
                  previewTab === "fields" ? "text-ink border-b-2 border-ink" : "text-sub hover:text-ink"
                }`}
              >
                Fields Summary
              </button>
            </div>
            
            <div className="flex-1 overflow-y-auto p-4">
              {previewTab === "preview" ? (
                <div className="overflow-hidden rounded-xl border border-hair">
                  <iframe
                    srcDoc={samplePreviewHtml}
                    className="w-full"
                    style={{ minHeight: 400 }}
                    title="Template Preview"
                  />
                </div>
              ) : (
                <div className="space-y-3">
                  <div className="rounded-xl border border-hair bg-paper p-4">
                    <div className="text-xs text-sub mb-2">Company Name</div>
                    <div className="text-sm text-ink font-medium">{name || "Not set"}</div>
                  </div>
                  
                  {fields.length > 0 ? (
                    <div className="rounded-xl border border-hair bg-paper p-4">
                      <div className="text-xs text-sub mb-3">Fields ({fields.length})</div>
                      <div className="space-y-2">
                        {fields.map((field) => (
                          <div key={field.key} className="flex items-center justify-between text-sm">
                            <span className="text-ink">{field.label}</span>
                            <span className="text-sub text-xs">
                              {field.type}
                              {field.locked ? " • locked" : ""}
                              {" • "}
                              {field.position}
                            </span>
                          </div>
                        ))}
                      </div>
                    </div>
                  ) : (
                    <div className="text-center py-6 text-sub text-sm">
                      No fields defined
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
        
        <div className="flex items-center justify-end gap-2 border-t border-hair px-6 py-4">
          <button onClick={onClose} className="px-4 py-2 text-xs text-sub hover:text-ink">
            Cancel
          </button>
          <button 
            onClick={save} 
            disabled={!name.trim() || fields.length === 0 || saving} 
            className="rounded-lg bg-indigo px-4 py-2 text-xs font-medium text-white hover:opacity-90 disabled:opacity-50"
          >
            {saving ? "Saving..." : "Save Template"}
          </button>
        </div>
      </div>
    </div>
  );
}
